name: .NET Download

on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Download
      run: |
        version=$(cat VERSION)
        dotnet new console -n MyDotNetApp
        cd MyDotNetApp || exit 1
        done
        for dir in Services/*/ ; do
            dirname="${dir%/}"
            dotnet add package "HuaweiCloud.SDK.${dirname##*/}" --version "$version"
        done
        cat MyDotNetApp.csproj || exit 1
      shell: bash
