name: .NET Download

on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Download
      run: |
        version=$(cat VERSION)
        services=$(find Services -maxdepth 1 -mindepth 1 -type d -printf "%f\n")
        dotnet new console -n MyDotNetApp
        cd MyDotNetApp || exit 1
        for service in "$services"; do
            # dotnet add package "HuaweiCloud.SDK.${service}" --version "$version"
            echo "HuaweiCloud.SDK.${service}"
        done
        cat MyDotNetApp.csproj || exit 1
      shell: bash
