# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:  
      matrix:  
        dotnet-version: [3.1.X, 5.0.X, 8.0.X]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
